#!/bin/python3

import math
import os
import random
import re
import sys
import re

n, m = map(int, input().split())
matrix = [list(input()) for _ in range(n)]
s = "".join(["".join(col) for col in zip(*matrix)])
print(re.sub(r"(?<=[a-zA-Z0-9])[^a-zA-Z0-9]+(?=[a-zA-Z0-9])", " ", s))


first_multiple_input = input().rstrip().split()

n = int(first_multiple_input[0])

m = int(first_multiple_input[1])

matrix = []

for _ in range(n):
    matrix_item = input()
    matrix.append(matrix_item)
